# Simple operations

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

x = [0,1,1,1,1,4]
print(x)
ROLLING_WINDOW = 2
print("Easy Example for window={}".format(ROLLING_WINDOW))

[0, 1, 1, 1, 1, 4]
Easy Example for window=2


In [2]:
# first ROLLING_WINDOW-1 items
padding = x[:(ROLLING_WINDOW-1)]
padding

[0]

In [3]:
# add padding
x = pd.DataFrame(np.concatenate([padding, x]))
print(x)

   0
0  0
1  0
2  1
3  1
4  1
5  1
6  4


In [4]:
# Calculate rolling mean
x = x.rolling(axis=0, window=ROLLING_WINDOW).mean()
print(x)

     0
0  NaN
1  0.0
2  0.5
3  1.0
4  1.0
5  1.0
6  2.5


In [5]:
# remove padding
x = x[(ROLLING_WINDOW-1):].values
print(x)

[[0. ]
 [0.5]
 [1. ]
 [1. ]
 [1. ]
 [2.5]]


# Apply to Tensor Data

In [6]:
########################################################
X = np.array([
          [[1,1,5],[1,1,1]],
          [[2,2,5],[2,2,5]],
          [[1,1,5],[1,1,5]],
          [[100,100,5],[3,3,500]],
          [[1,2,5],[3,4,5]],
          [[2,2,5],[2,2,5]],
          [[1,1,5],[1,1,5]],
          [[1,2,5],[3,4,5]],
          [[2,2,5],[2,2,5]],
          [[1,1,5],[1,1,5]],
          [[1,2,5],[3,4,5]],
          [[2,2,5],[2,2,5]],
          [[1,1,5],[1,1,5]],
          [[1,1,5],[1,1,5]],
          [[2,2,5],[2,2,5]],
          [[1,1,5],[1,1,5]],
          [[4,3,5],[2,1,5]]
         ])
ROLLING_WINDOW = 5

In [7]:
X.shape

(17, 2, 3)

In [8]:
# Known Anomaly
X[3]

array([[100, 100,   5],
       [  3,   3, 500]])

In [9]:
# first ROLLING_WINDOW-1 items as padding
padding = X[:(ROLLING_WINDOW-1)]
padding

array([[[  1,   1,   5],
        [  1,   1,   1]],

       [[  2,   2,   5],
        [  2,   2,   5]],

       [[  1,   1,   5],
        [  1,   1,   5]],

       [[100, 100,   5],
        [  3,   3, 500]]])

In [10]:
# add padding
X_add_padding = np.concatenate([padding, X])
print(X_add_padding.shape)

(21, 2, 3)


In [11]:
df = pd.Panel(X_add_padding).to_frame()
print(df)
print("{} days {} samples (time-windows) {} features (messages)".format(*X.shape))

             0   1   2    3   4   5   6    7   8   9  ...  11  12  13  14  15  \
major minor                                           ...                       
0     0       1   2   1  100   1   2   1  100   1   2 ...   1   2   1   1   2   
      1       1   2   1  100   1   2   1  100   2   2 ...   2   2   1   2   2   
      2       5   5   5    5   5   5   5    5   5   5 ...   5   5   5   5   5   
1     0       1   2   1    3   1   2   1    3   3   2 ...   3   2   1   3   2   
      1       1   2   1    3   1   2   1    3   4   2 ...   4   2   1   4   2   
      2       1   5   5  500   1   5   5  500   5   5 ...   5   5   5   5   5   

             16  17  18  19  20  
major minor                      
0     0       1   1   2   1   4  
      1       1   1   2   1   3  
      2       5   5   5   5   5  
1     0       1   1   2   1   2  
      1       1   1   2   1   1  
      2       5   5   5   5   5  

[6 rows x 21 columns]
17 days 2 samples (time-windows) 3 features (messages)


In [12]:
df.rolling(axis=1, window=ROLLING_WINDOW).mean()

0   1   2   3      4      5      6      7      8      9  ...   \
major minor                                                           ...    
0     0     NaN NaN NaN NaN   21.0   21.2   21.0   40.8   21.0   21.2 ...    
      1     NaN NaN NaN NaN   21.0   21.2   21.0   40.8   21.2   21.4 ...    
      2     NaN NaN NaN NaN    5.0    5.0    5.0    5.0    5.0    5.0 ...    
1     0     NaN NaN NaN NaN    1.6    1.8    1.6    2.0    2.0    2.2 ...    
      1     NaN NaN NaN NaN    1.6    1.8    1.6    2.0    2.2    2.4 ...    
      2     NaN NaN NaN NaN  102.4  103.2  103.2  202.2  103.2  104.0 ...    

                11   12   13   14   15   16   17   18   19   20  
major minor                                                      
0     0       21.0  1.4  1.4  1.2  1.4  1.4  1.2  1.4  1.4  1.8  
      1       21.4  1.8  1.6  1.6  1.8  1.6  1.4  1.6  1.4  1.6  
      2        5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  
1     0        2.4  2.2  1.8  2.0  2.2  1.8  1.6  1.8  1.4  1.4  
      1        2.8  2.6  2.0  2.4  2.6  2.0  1.8  2.0  1.4  1.2  
      2      104.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  5.0  

[6 rows x 21 columns]

In [13]:
df = df - df.rolling(axis=1, window=ROLLING_WINDOW).mean()
df

0   1   2   3      4     5     6      7     8     9  ...     11  \
major minor                                                       ...          
0     0     NaN NaN NaN NaN  -20.0 -19.2 -20.0   59.2 -20.0 -19.2 ...  -20.0   
      1     NaN NaN NaN NaN  -20.0 -19.2 -20.0   59.2 -19.2 -19.4 ...  -19.4   
      2     NaN NaN NaN NaN    0.0   0.0   0.0    0.0   0.0   0.0 ...    0.0   
1     0     NaN NaN NaN NaN   -0.6   0.2  -0.6    1.0   1.0  -0.2 ...    0.6   
      1     NaN NaN NaN NaN   -0.6   0.2  -0.6    1.0   1.8  -0.4 ...    1.2   
      2     NaN NaN NaN NaN -101.4 -98.2 -98.2  297.8 -98.2 -99.0 ...  -99.0   

              12   13   14   15   16   17   18   19   20  
major minor                                               
0     0      0.6 -0.4 -0.2  0.6 -0.4 -0.2  0.6 -0.4  2.2  
      1      0.2 -0.6  0.4  0.2 -0.6 -0.4  0.4 -0.4  1.4  
      2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0     -0.2 -0.8  1.0 -0.2 -0.8 -0.6  0.2 -0.4  0.6  
      1     -0.6 -1.0  1.6 -0.6 -1.0 -0.8  0.0 -0.4 -0.2  
      2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[6 rows x 21 columns]

In [14]:
X_reconstructed =  df.values.T.reshape(X_add_padding.shape)
X_reconstructed.shape

(21, 2, 3)

In [15]:
# remove padding
X_reconstructed = X_reconstructed[(ROLLING_WINDOW-1):]
X_reconstructed.shape

(17, 2, 3)

In [16]:
print("\nMean on axis 0\n")
M = X_reconstructed.mean(axis = 0)
print(M)

print("\nStd on axis 0\n")
S = X_reconstructed.std(axis = 0)
print(S)


Mean on axis 0

[[ -4.51764706  -4.56470588   0.        ]
 [ -0.04705882  -0.09411765 -23.24705882]]

Std on axis 0

[[18.63179557 18.55335521  0.        ]
 [ 0.65987311  0.9077902  93.34070493]]


In [17]:
day_idx, window_idx, message_idx = np.where(np.abs(X_reconstructed - M) > 3 * S)

In [18]:
print("\nAnomalies:")
print(list(zip(day_idx, window_idx, message_idx)))


Anomalies:
[(3, 0, 0), (3, 0, 1), (3, 1, 2)]


In [19]:
X[0]

array([[1, 1, 5],
       [1, 1, 1]])

# Object Oriented Coding

In [20]:

class statistical_anomaly_detector():
    def __init__(self, X, ROLLING_WINDOW = 5):
        self.X = X
        self.ROLLING_WINDOW = ROLLING_WINDOW
        print("{} days {} samples (time-windows) {} features (messages)".format(*self.X.shape))
        
    def fit_predict(self):
        padding = self.X[:(self.ROLLING_WINDOW-1)]
        X_add_padding = np.concatenate([padding, self.X])
        df = pd.Panel(X_add_padding).to_frame()
        
        df.rolling(axis=1, window=self.ROLLING_WINDOW).mean()
        df = df - df.rolling(axis=1, window=self.ROLLING_WINDOW).mean()
        
        X_reconstructed =  df.values.T.reshape(X_add_padding.shape)
        # remove padding
        X_reconstructed = X_reconstructed[(self.ROLLING_WINDOW-1):]
        
        self.M = X_reconstructed.mean(axis = 0)
        self.S = X_reconstructed.std(axis = 0)
        
        day_idx, window_idx, message_idx = np.where(np.abs(X_reconstructed - self.M) > 3 * self.S)
        return list(zip(day_idx, window_idx, message_idx))


In [21]:
SAD = statistical_anomaly_detector(X)

17 days 2 samples (time-windows) 3 features (messages)


In [22]:
SAD.fit_predict()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  """Entry point for launching an IPython kernel.


[(3, 0, 0), (3, 0, 1), (3, 1, 2)]