## Veri Bilimine Giris
- https://www.kaggle.com/kanncaa1/data-sciencetutorial-for-beginners
 

## Makine Ogrenmesine Giris
 - https://colab.research.google.com/drive/1t7DwPvKZN1mIoiOOHDLHVG9xifGxrJES
 
 
---

# Metin Isleme

 - Bu ornek kod ve veri icin su dersten yararlanilmistir: https://www.udemy.com/machinelearning/

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)
dataset.head(7)

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0

In [2]:
pd.read_csv?

In [3]:
dataset.Review[0:3]

0                     Wow... Loved this place.
1                           Crust is not good.
2    Not tasty and the texture was just nasty.
Name: Review, dtype: object

In [4]:
for i in range(3):
    print(dataset.Review[i], "  -->  ", dataset.Liked[i])

Wow... Loved this place.   -->   1
Crust is not good.   -->   0
Not tasty and the texture was just nasty.   -->   0


In [5]:
# Cleaning the texts
import re
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [6]:
# harf olmayan her seyden kurtularak ilk reviewi yaz
review = re.sub('[^a-zA-Z]', '<>', dataset['Review'][0])
review

'Wow<><><><>Loved<>this<>place<>'

In [7]:
review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][0])
review

'Wow    Loved this place '

In [8]:
review = review.lower()
review

'wow    loved this place '

In [9]:
review = review.split()
review

['wow', 'loved', 'this', 'place']

# Stopwordsden kurtul

In [10]:
ps = PorterStemmer()
anlamsiz = set(stopwords.words('english')) # Stopwords = anlamsiz kelimeler

In [11]:
review = [ps.stem(word) for word in review if not word in anlamsiz]
review

['wow', 'love', 'place']

In [12]:
review = ' '.join(review)
review

'wow love place'

# Corpus olustur


In [13]:
n = len(dataset)
n

1000

In [14]:
corpus = []
for i in range(n):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [15]:
# islenmeden once
dataset.Review[0:3]

0                     Wow... Loved this place.
1                           Crust is not good.
2    Not tasty and the texture was just nasty.
Name: Review, dtype: object

In [16]:
# islendikten sonra
corpus[:3]

['wow love place', 'crust good', 'tasti textur nasti']

In [17]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [18]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
X.shape

(1000, 1500)

In [20]:
cv2 = CountVectorizer(vocabulary=['hot', 'cold', 'old'])
quotes = ['I want hot dog', 'very cold here', 'Hello World', 'old good days, old, old older']

In [21]:
# tokenize and build vocab
cv2.fit(quotes)
# summarize
print(cv2.vocabulary_)

{'hot': 0, 'cold': 1, 'old': 2}


In [22]:
# encode document
vq = cv2.transform(quotes)
vq.toarray()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 3]])

In [23]:
text = ["Old but not cold"]
cv2.transform(text).toarray()

array([[0, 1, 1]])

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ["The quick brown fox jumped over the lazy dog.", "The dog.", "The fox"]
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(vectorizer.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [25]:
print(vectorizer.idf_)

[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


In [26]:
# encode document
vector = vectorizer.transform([text[0]])
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(1, 8)
[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]]


In [27]:
dict(zip(vectorizer.get_feature_names(), vectorizer.idf_))

{'brown': 1.6931471805599454,
 'dog': 1.2876820724517808,
 'fox': 1.2876820724517808,
 'jumped': 1.6931471805599454,
 'lazy': 1.6931471805599454,
 'over': 1.6931471805599454,
 'quick': 1.6931471805599454,
 'the': 1.0}

# Tum Kod

In [32]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

# Cleaning the texts
import re
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("confusion_matrix:\n", cm)
print("accuracy_score: ", accuracy_score(y_test, y_pred))

confusion_matrix:
 [[55 42]
 [12 91]]
accuracy_score:  0.73


In [31]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("confusion_matrix:\n", cm)
print("accuracy_score: ", accuracy_score(y_test, y_pred))

confusion_matrix:
 [[76 21]
 [37 66]]
accuracy_score:  0.71


In [33]:
from sklearn.neural_network import MLPClassifier
nn=MLPClassifier(hidden_layer_sizes=(7,), max_iter=1000, alpha=0.1,
                     solver='sgd', verbose=10,  random_state=21,tol=0.000000001)

nn.fit(X_train,y_train)
# Predicting the Test set results
y_pred = nn.predict(X_test)


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("confusion_matrix:\n", cm)
print("accuracy_score: ", accuracy_score(y_test, y_pred))

Iteration 1, loss = 0.69991404
Iteration 2, loss = 0.69980740
Iteration 3, loss = 0.69964833
Iteration 4, loss = 0.69944994
Iteration 5, loss = 0.69923223
Iteration 6, loss = 0.69899730
Iteration 7, loss = 0.69876183
Iteration 8, loss = 0.69851880
Iteration 9, loss = 0.69827539
Iteration 10, loss = 0.69802227
Iteration 11, loss = 0.69777449
Iteration 12, loss = 0.69752192
Iteration 13, loss = 0.69727723
Iteration 14, loss = 0.69702605
Iteration 15, loss = 0.69679059
Iteration 16, loss = 0.69653214
Iteration 17, loss = 0.69628576
Iteration 18, loss = 0.69604629
Iteration 19, loss = 0.69580643
Iteration 20, loss = 0.69555737
Iteration 21, loss = 0.69530771
Iteration 22, loss = 0.69506792
Iteration 23, loss = 0.69482589
Iteration 24, loss = 0.69458039
Iteration 25, loss = 0.69435104
Iteration 26, loss = 0.69409850
Iteration 27, loss = 0.69386279
Iteration 28, loss = 0.69361924
Iteration 29, loss = 0.69338576
Iteration 30, loss = 0.69314717
Iteration 31, loss = 0.69289529
Iteration 32, los

Iteration 258, loss = 0.62569737
Iteration 259, loss = 0.62532741
Iteration 260, loss = 0.62495393
Iteration 261, loss = 0.62456711
Iteration 262, loss = 0.62419661
Iteration 263, loss = 0.62381762
Iteration 264, loss = 0.62345000
Iteration 265, loss = 0.62307333
Iteration 266, loss = 0.62268998
Iteration 267, loss = 0.62231311
Iteration 268, loss = 0.62193686
Iteration 269, loss = 0.62155374
Iteration 270, loss = 0.62117515
Iteration 271, loss = 0.62079711
Iteration 272, loss = 0.62041746
Iteration 273, loss = 0.62003090
Iteration 274, loss = 0.61965636
Iteration 275, loss = 0.61927228
Iteration 276, loss = 0.61889650
Iteration 277, loss = 0.61849987
Iteration 278, loss = 0.61812332
Iteration 279, loss = 0.61774273
Iteration 280, loss = 0.61735514
Iteration 281, loss = 0.61697602
Iteration 282, loss = 0.61658824
Iteration 283, loss = 0.61619768
Iteration 284, loss = 0.61582238
Iteration 285, loss = 0.61543259
Iteration 286, loss = 0.61504819
Iteration 287, loss = 0.61465238
Iteration 

Iteration 515, loss = 0.51831629
Iteration 516, loss = 0.51788098
Iteration 517, loss = 0.51745266
Iteration 518, loss = 0.51701324
Iteration 519, loss = 0.51658159
Iteration 520, loss = 0.51615583
Iteration 521, loss = 0.51572352
Iteration 522, loss = 0.51531245
Iteration 523, loss = 0.51486323
Iteration 524, loss = 0.51444334
Iteration 525, loss = 0.51400471
Iteration 526, loss = 0.51357944
Iteration 527, loss = 0.51314366
Iteration 528, loss = 0.51272432
Iteration 529, loss = 0.51228928
Iteration 530, loss = 0.51187049
Iteration 531, loss = 0.51142890
Iteration 532, loss = 0.51100870
Iteration 533, loss = 0.51057844
Iteration 534, loss = 0.51014771
Iteration 535, loss = 0.50972463
Iteration 536, loss = 0.50928988
Iteration 537, loss = 0.50887109
Iteration 538, loss = 0.50844349
Iteration 539, loss = 0.50800952
Iteration 540, loss = 0.50757862
Iteration 541, loss = 0.50716346
Iteration 542, loss = 0.50673270
Iteration 543, loss = 0.50630704
Iteration 544, loss = 0.50587718
Iteration 

Iteration 785, loss = 0.41084064
Iteration 786, loss = 0.41047812
Iteration 787, loss = 0.41011987
Iteration 788, loss = 0.40977988
Iteration 789, loss = 0.40942174
Iteration 790, loss = 0.40907838
Iteration 791, loss = 0.40871168
Iteration 792, loss = 0.40836071
Iteration 793, loss = 0.40801032
Iteration 794, loss = 0.40766586
Iteration 795, loss = 0.40731752
Iteration 796, loss = 0.40697110
Iteration 797, loss = 0.40662165
Iteration 798, loss = 0.40626444
Iteration 799, loss = 0.40591488
Iteration 800, loss = 0.40556938
Iteration 801, loss = 0.40522360
Iteration 802, loss = 0.40486427
Iteration 803, loss = 0.40452685
Iteration 804, loss = 0.40417438
Iteration 805, loss = 0.40383716
Iteration 806, loss = 0.40348687
Iteration 807, loss = 0.40313360
Iteration 808, loss = 0.40279202
Iteration 809, loss = 0.40244659
Iteration 810, loss = 0.40209716
Iteration 811, loss = 0.40175121
Iteration 812, loss = 0.40140781
Iteration 813, loss = 0.40107214
Iteration 814, loss = 0.40072044
Iteration 

/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# Siradaki Isler

Spam/Ham
 - https://github.com/shreyans29/thesemicolon/blob/master/Text%20Analytics%20CV.ipynb

NLP
 - https://dzone.com/articles/nlp-tutorial-using-python-nltk-simple-examples

# Hipotez Testi

In [36]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import quandl
quandl.ApiConfig.api_key = 'tAyfv1zpWnyhmDsp91yv'
#get data from quandl
spy_table = quandl.get('BCIW/_SPXT')
spy_total = spy_table[['Open','Close']]
#calculate log returns
spy_log_return = np.log(spy_total.Close).diff().dropna()
print('Population mean:', np.mean(spy_log_return))


Population mean: 0.000542769162599561


In [37]:
print('10 days sample returns:', np.mean(spy_log_return.tail(10)))

10 days sample returns: 0.0005199499813855369


In [38]:
print('10 days sample returns:', np.mean(spy_log_return.tail(1000)))

10 days sample returns: 0.000542769162599561


> As we expected, the two samples has different means and variances.